# Generated by Django 4.2.6 on 2023-10-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_airplane_name_alter_airport_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(related_name="flights", to="airport.crew"),
        ),
    ]
